CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE ideas (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    explanation TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    votes INT DEFAULT 0 NOT NULL
);
